# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='protocole',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0eprotocol.proto\x12\tprotocole\"\x86\x01\n\x06Header\x12\x11\n\tmsgLength\x18\x01 \x02(\x05\x12*\n\x07msgType\x18\x02 \x02(\x0e\x32\x19.protocole.Header.MsgType\"=\n\x07MsgType\x12\t\n\x05LOGIN\x10\x00\x12\r\n\tSTATEMENT\x10\x01\x12\x08\n\x04\x45\x44IT\x10\x02\x12\x0e\n\nPUBLIC_KEY\x10\x03\",\n\tLoginInfo\x12\r\n\x05login\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\xbb\x01\n\tStatement\x12\'\n\x04info\x18\x01 \x02(\x0e\x32\x19.protocole.Statement.Info\"\x84\x01\n\x04Info\x12\x0e\n\nKEEP_ALIVE\x10\x00\x12\x11\n\rREQUEST_LOGIN\x10\x01\x12\x12\n\x0eLOGIN_ACCEPTED\x10\x02\x12\x12\n\x0eLOGIN_REJECTED\x10\x03\x12\x0b\n\x07LOG_OUT\x10\x04\x12\x0c\n\x08WORK_END\x10\x05\x12\x16\n\x12PUBLIC_KEY_REQUEST\x10\x06\"\x14\n\x04\x45\x64it\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\"a\n\x03Key\x12\'\n\x07keyType\x18\x01 \x02(\x0e\x32\x16.protocole.Key.KeyType\x12\x0b\n\x03key\x18\x02 \x02(\t\"$\n\x07KeyType\x12\r\n\tSYMMETRIC\x10\x00\x12\n\n\x06PUBLIC\x10\x01'
)



_HEADER_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='protocole.Header.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOGIN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATEMENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EDIT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC_KEY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=103,
  serialized_end=164,
)
_sym_db.RegisterEnumDescriptor(_HEADER_MSGTYPE)

_STATEMENT_INFO = _descriptor.EnumDescriptor(
  name='Info',
  full_name='protocole.Statement.Info',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KEEP_ALIVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_LOGIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_ACCEPTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_REJECTED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOG_OUT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK_END', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC_KEY_REQUEST', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=268,
  serialized_end=400,
)
_sym_db.RegisterEnumDescriptor(_STATEMENT_INFO)

_KEY_KEYTYPE = _descriptor.EnumDescriptor(
  name='KeyType',
  full_name='protocole.Key.KeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYMMETRIC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=485,
  serialized_end=521,
)
_sym_db.RegisterEnumDescriptor(_KEY_KEYTYPE)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='protocole.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgLength', full_name='protocole.Header.msgLength', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='protocole.Header.msgType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEADER_MSGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=164,
)


_LOGININFO = _descriptor.Descriptor(
  name='LoginInfo',
  full_name='protocole.LoginInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='protocole.LoginInfo.login', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='protocole.LoginInfo.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=210,
)


_STATEMENT = _descriptor.Descriptor(
  name='Statement',
  full_name='protocole.Statement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='protocole.Statement.info', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATEMENT_INFO,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=400,
)


_EDIT = _descriptor.Descriptor(
  name='Edit',
  full_name='protocole.Edit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='protocole.Edit.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=422,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='protocole.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyType', full_name='protocole.Key.keyType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='protocole.Key.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KEY_KEYTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=521,
)

_HEADER.fields_by_name['msgType'].enum_type = _HEADER_MSGTYPE
_HEADER_MSGTYPE.containing_type = _HEADER
_STATEMENT.fields_by_name['info'].enum_type = _STATEMENT_INFO
_STATEMENT_INFO.containing_type = _STATEMENT
_KEY.fields_by_name['keyType'].enum_type = _KEY_KEYTYPE
_KEY_KEYTYPE.containing_type = _KEY
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['LoginInfo'] = _LOGININFO
DESCRIPTOR.message_types_by_name['Statement'] = _STATEMENT
DESCRIPTOR.message_types_by_name['Edit'] = _EDIT
DESCRIPTOR.message_types_by_name['Key'] = _KEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocole.Header)
  })
_sym_db.RegisterMessage(Header)

LoginInfo = _reflection.GeneratedProtocolMessageType('LoginInfo', (_message.Message,), {
  'DESCRIPTOR' : _LOGININFO,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocole.LoginInfo)
  })
_sym_db.RegisterMessage(LoginInfo)

Statement = _reflection.GeneratedProtocolMessageType('Statement', (_message.Message,), {
  'DESCRIPTOR' : _STATEMENT,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocole.Statement)
  })
_sym_db.RegisterMessage(Statement)

Edit = _reflection.GeneratedProtocolMessageType('Edit', (_message.Message,), {
  'DESCRIPTOR' : _EDIT,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocole.Edit)
  })
_sym_db.RegisterMessage(Edit)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocole.Key)
  })
_sym_db.RegisterMessage(Key)


# @@protoc_insertion_point(module_scope)
